name: Publish to NPM
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Instal
        run: npm install

      - name: Clean
        run: |
          git add .
          git commit -m "Committing changes before version bump" || echo "No changes to commit"

      - name: Publish
        run: |
          npm version minor -m "Bump version to %s"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm }}
