name: Publish to NPM
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Bump version and commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          npm version minor -m "Bump version to %s"
          git add package.json package-lock.json
          git commit -m "Bump version to %s"
          git push

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm }}
